language: java
jdk: openjdk8

sudo: required

notifications:
  email:
    recipients:
      - randhir.raj@gmail.com
    on_success: never
    on_failure: always

before_install:
  - chmod +x mvnw

after_success:
  - bash <(curl -s https://codecov.io/bash)